### ISSUE TITLE
Release 1.6.0 is unavailable

### ISSUE THREAD

**Issue by spremel** [norwoodj/helm-docs#117]
The release 1.6.0 associated to the tag v1.6.0 is unavailable.

This is likely due to the failed CI pipeline "goreleaser" : https://github.com/norwoodj/helm-docs/runs/3073182310?check_suite_focus=true

Would it be possible to add the release ?
Thank you

**Comment by skang0601** [comment]
@spremel Thanks for the issue! I'll take a look at this later today.

**Comment by mcamenzind** [comment]
@norwoodj @skang0601 
In the process of adding 1.6.0 to the Github releases page, could you also add the compile version for M1? Thank you!

**Comment by stranljip** [comment]
Hi - is there an update on this? My hope is that the issue with Homebrew is gone after a release and my quick-and-dirty fix won't be needed norwoodj/homebrew-tap#2

**Comment by dwerder** [comment]
Any news on that?

**Comment by stranljip** [comment]
Ping ... I am getting annoyed by the constant warning in my Homebrew output - could you please either release 1.6.0 with a subsequent update of the Homebrew formula or merge my quick-and-dirty-fix norwoodj/homebrew-tap#2? Seeing the lack of responses here I am thinking about forking it only for the sake of getting rid of that warning :-/ If you need help in (re-)releasing the version I would be willing to help - but please say so :-)

**Comment by sc250024** [comment]
I am also getting a bit concerned over the inactivity of the maintainers on this project. There are now multiple large projects depending on this tool (including [kubernetes/autoscaler](https://github.com/kubernetes/autoscaler/blob/master/charts/cluster-autoscaler/README.md.gotmpl) and [kubernetes/ingress-nginx](https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/README.md.gotmpl)), and the release cadence is a bit lacking.

- 4 months between [v1.5.0](https://github.com/norwoodj/helm-docs/releases/tag/v1.5.0) and [v1.6.0](https://github.com/norwoodj/helm-docs/releases/tag/v1.6.0), and no release
- No releases since [v1.6.0](https://github.com/norwoodj/helm-docs/releases/tag/v1.6.0) (7 months)
- Important PRs needing attention: https://github.com/norwoodj/helm-docs/pull/99

**Comment by sagikazarmark** [comment]
1.7.0 has just been tagged.....but something really weird is going on: https://github.com/norwoodj/homebrew-tap/commit/6245567c719b53a58da439e67d1d4441dc8ab564

**Comment by james-pollard-leapyear** [comment]
I'm also seeing that `jnorwood/helm-docs:latest` is associated with v1.6 instead of v1.7
