### ISSUE TITLE
Table is outputted alphabetically rather than as-per values.yaml

### ISSUE THREAD

**Issue by robertgates55** [norwoodj/helm-docs#44]
I wondered if I'm missing anything - I was hoping to have my values table outputted in the same order that the yaml is laid out. Is that possible?

**Comment by norwoodj** [comment]
Hey @robertgates55, sorry for the slow response, due to carpal tunnel issues I've been having the last few months, I've had to ignore this repository for the most part. As implemented, there's no way of knowing the order that the original yaml file had its keys laid out in. Alphabetical ordering was the best I could do. Sorry!
