### ISSUE TITLE
Recursive documentation in one README file

### ISSUE THREAD

**Issue by DivyaSundar-89** [norwoodj/helm-docs#70]
Dear maintainers,

Firstly, this is a great tool for producing the documentation. In my case, i have a helm chart with lot of dependencies packed in a tar.gz file. Is it possible to generate one README file with the values from all the dependent charts instead of the README recursively generated in all the sub-chart directories.

**Comment by aeciopires** [comment]
I agree with @DivyaSundar-89. The tool is excellent and has helped me a lot to document the charts I use at work and other open source projects. I met the tool a few months ago working with @matheusfm 

I think that in addition to the recursive values it would be very good if it were possible to recursively obtain all other information from the charts.

In this way, it would be possible to create a central README at the beginning of the repository containing all information about all the charts that are within one or more directories.

**Comment by norwoodj** [comment]
I think this is a reasonable ask. I assume what you mean is that the root chart has a bunch of sub-charts specified in `requirements.yaml` (or `Chart.yaml` if helm v2). I can envision a new flag `--document-requirement-charts` or similar that documents these dependended-upon charts in the root chart README.

I don't have time to do this work at present, but feel free to submit a PR. Otherwise, I'll get to it when I have time.

**Comment by DivyaSundar-89** [comment]
Yes, since we have multiple sub-charts as dependencies, the dependent charts values can be documented in the root chart README to maintain a single README file.

**Comment by norwoodj** [comment]
Fixed by #112
